"""Extract the empirical contract of the trained model artifacts.

Answers the six questions from SPRINTS.md §7.3 and writes them into
:file:`models/MODEL_CARD.md`. Run manually (Sprint 6):

    .venv/Scripts/python.exe scripts/inspect_model.py

Requires the ``inference-keras`` and ``inference-onnx`` optional extras
(``uv sync --extra inference-keras --extra inference-onnx``).
"""

from __future__ import annotations

import argparse
import json
import os
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

# Silence TensorFlow's C++ chatter before it prints its banner.
os.environ.setdefault("TF_CPP_MIN_LOG_LEVEL", "3")
os.environ.setdefault("TF_ENABLE_ONEDNN_OPTS", "0")


def _keras_summary(model_path: Path) -> dict[str, Any]:
    import keras

    model = keras.models.load_model(model_path, compile=False)
    inputs = [
        {
            "name": layer.name,
            "shape": tuple(int(d) if d is not None else -1 for d in layer.shape),
            "dtype": str(layer.dtype),
        }
        for layer in model.inputs
    ]
    outputs = [
        {
            "name": layer.name,
            "shape": tuple(int(d) if d is not None else -1 for d in layer.shape),
            "dtype": str(layer.dtype),
        }
        for layer in model.outputs
    ]

    # Look up the final activation to know if the output is bounded.
    final_activation = None
    try:
        gaze_layer = model.get_layer("gaze_xy")
        final_activation = gaze_layer.get_config().get("activation")
    except ValueError:
        final_activation = "unknown (no 'gaze_xy' layer)"

    total_params = int(model.count_params())
    return {
        "inputs": inputs,
        "outputs": outputs,
        "final_activation": final_activation,
        "total_params": total_params,
    }


def _onnx_summary(model_path: Path) -> dict[str, Any]:
    import onnxruntime as ort

    sess = ort.InferenceSession(str(model_path), providers=["CPUExecutionProvider"])
    inputs = [
        {"name": i.name, "shape": list(i.shape), "type": i.type}
        for i in sess.get_inputs()
    ]
    outputs = [
        {"name": o.name, "shape": list(o.shape), "type": o.type}
        for o in sess.get_outputs()
    ]
    return {"inputs": inputs, "outputs": outputs}


def _classify_onnx(onnx: dict[str, Any]) -> str:
    if len(onnx["outputs"]) != 1:
        return "unknown (multiple outputs)"
    shape = onnx["outputs"][0]["shape"]
    static_tail = [dim for dim in shape[1:] if isinstance(dim, int)]
    if static_tail == [2]:
        return "gaze_xy (full estimator)"
    if len(static_tail) == 1 and static_tail[0] > 2:
        return f"embedding of size {static_tail[0]} (encoder only — NOT a full estimator)"
    return f"unclassified — shape={shape!r}"


def _render_card(
    *,
    keras_info: dict[str, Any],
    onnx_info: dict[str, Any],
    keras_path: Path,
    onnx_path: Path,
    generated_at: str,
) -> str:
    onnx_kind = _classify_onnx(onnx_info)

    def _tensor_row(t: dict[str, Any]) -> str:
        return (
            f"| `{t['name']}` | `{tuple(t['shape'])}` | "
            f"`{t.get('dtype', t.get('type', '?'))}` |"
        )

    keras_input_rows = "\n".join(_tensor_row(t) for t in keras_info["inputs"])
    keras_output_rows = "\n".join(_tensor_row(t) for t in keras_info["outputs"])
    onnx_input_rows = "\n".join(_tensor_row(t) for t in onnx_info["inputs"])
    onnx_output_rows = "\n".join(_tensor_row(t) for t in onnx_info["outputs"])

    final_activation = keras_info["final_activation"]
    output_is_bounded = final_activation == "sigmoid"

    return f"""# IrisFlow MODEL_CARD

Auto-generated by `scripts/inspect_model.py` — regenerate whenever the
artifacts under `models/` are replaced.

- **Generated**: {generated_at}
- **Keras artifact**: `{keras_path.as_posix()}`
- **ONNX artifact**: `{onnx_path.as_posix()}`

## 1. Input names and order

The four inputs of the trained CNN, exactly as they appear in the
artifact (Keras assigns names, positional order isn't guaranteed):

| Name | Shape (batch = 1 implied) | dtype |
|------|---------------------------|-------|
{keras_input_rows}

The ONNX file exposes the same four inputs with matching shapes:

| Name | Shape | Type |
|------|-------|------|
{onnx_input_rows}

## 2. Channel layout — RGB or BGR

**Cannot be determined from the artifacts alone.** The recorded input
dtype is `float32`, but neither Keras nor ONNX serialize the channel
order the training pipeline used.

**Decision**: use `RGB` as declared in `configs/default.yaml`
(`model.channel_order: RGB`) and validate empirically with the Sprint 6
sanity check (`irisflow bench --sanity-check`). If a real face fixture
produces obviously-wrong gaze (e.g. horizontally mirrored), flip to `BGR`
and rerun. **Do NOT ship without the sanity check passing.**

## 3. Normalization scheme

**Cannot be determined from the artifacts alone.** No preprocessing
layer is baked into the graph (verified by inspecting layer types).

**Decision**: keep `normalization: unit` (`x / 255`) as configured. If
sanity check reveals gaze bias, try `signed` (`x/127.5 - 1`) and
`imagenet` in turn. Whichever produces a centred output for a centred
face is the correct one.

## 4. Semantics of the 12-dim `rect` vector

**Cannot be determined from the artifacts alone** — the vector is passed
through as-is by the CNN.

**Assumed layout** (from SPRINTS.md §7.4 — the iTracker/GazeCapture
convention):

| Index | Field | Normalization |
|-------|-------|---------------|
| 0-3   | `face.x, face.y, face.w, face.h` | `/W, /H, /W, /H` |
| 4-7   | `left_eye.x, left_eye.y, left_eye.w, left_eye.h` | idem |
| 8-11  | `right_eye.x, right_eye.y, right_eye.w, right_eye.h` | idem |

- `(x, y)` = **top-left corner** (not centre).
- Coordinates relative to the **full frame** (not to the face crop).
- "Left" / "right" = **subject's** left/right.

This is what `irisflow.preprocessing.rect_vector.build_rect_vector`
emits. If sanity check fails despite correct channel order and
normalization, this section is the next likely culprit.

## 5. What is `gaze_encoder.onnx`?

**Classification: {onnx_kind}.**

| Name | Shape | Type |
|------|-------|------|
{onnx_output_rows}

Because the ONNX file exposes only the trunk's embedding, **it cannot be
used as a drop-in production backend for gaze estimation**. Two
consequences:

* Sprint 6's "paridade Keras x ONNX" criterion is satisfied by
  documenting this here — see SPRINTS.md §8 Sprint 6 acceptance list.
* `irisflow.inference.onnx_backend.OnnxBackend` still exists so a future
  export of the full graph can be plugged in with a config change; today
  it raises a clear `InferenceError` at construction if the loaded model
  emits an embedding.

## 6. Axis convention (`y` up or down?)

**Cannot be determined from the artifacts alone.** The output layer
(`gaze_xy`, Dense units=2, activation=`{final_activation}`) yields two
values in `[0, 1]` — the *meaning* of each axis is a training-side
decision.

**Decision**: assume `(x_normalized, y_normalized)` with **image
convention** (`y` increases downward, same as `Frame` coordinates). Sanity
check: with the user looking at the four screen corners, the outputs must
separate monotonically. If top-of-screen produces `y > 0.5` instead of
`y < 0.5`, flip the axis in `mapping.screen.to_screen`.

## Keras architecture summary

- Total params: {keras_info["total_params"]:,}
- Final activation: `{final_activation}`
- Output shape: `{keras_info["outputs"][0]["shape"]}`
- Output bounded to `[0, 1]²`: **{"yes (sigmoid)" if output_is_bounded else "no"}**

| Output tensor | Shape | dtype |
|---------------|-------|-------|
{keras_output_rows}

---

## Sanity check log

Populate after running `irisflow bench --sanity-check` against real
capture. Each row is one condition (centre, four corners).

| Condition | Expected | Observed x | Observed y | Pass? |
|-----------|----------|------------|------------|-------|
| Centre    | ~0.50, ~0.50 | | | |
| Top-left  | x low, y low | | | |
| Top-right | x high, y low | | | |
| Bottom-left | x low, y high | | | |
| Bottom-right | x high, y high | | | |
"""


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--keras",
        type=Path,
        default=Path("models/gaze_cnn_best.keras"),
        help="Path to the Keras artifact.",
    )
    parser.add_argument(
        "--onnx",
        type=Path,
        default=Path("models/gaze_encoder.onnx"),
        help="Path to the ONNX artifact.",
    )
    parser.add_argument(
        "--out",
        type=Path,
        default=Path("models/MODEL_CARD.md"),
        help="Where to write the model card.",
    )
    parser.add_argument(
        "--json",
        action="store_true",
        help="Also print a JSON summary to stdout (for CI).",
    )
    args = parser.parse_args()

    keras_info = _keras_summary(args.keras)
    onnx_info = _onnx_summary(args.onnx)

    generated_at = datetime.now(UTC).isoformat(timespec="seconds")
    card = _render_card(
        keras_info=keras_info,
        onnx_info=onnx_info,
        keras_path=args.keras,
        onnx_path=args.onnx,
        generated_at=generated_at,
    )
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(card, encoding="utf-8")

    if args.json:
        print(
            json.dumps(
                {"keras": keras_info, "onnx": onnx_info, "written_to": str(args.out)},
                indent=2,
                default=str,
            )
        )
    else:
        print(f"Wrote {args.out}")
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
